name: 🐛 Bug Report
description: Report a bug in the codebase
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the information below to document the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug clearly. Include expected vs actual behavior.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: Optional - add screenshots or logs if relevant
      placeholder: Paste screenshots or logs here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I can reproduce this issue consistently
          required: false
        - label: I have reproduced the issue locally
          required: false
