name: 🧹 Chore
description: General maintenance tasks
title: "[CHORE]: "
labels: ["maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for general maintenance tasks like dependency updates, code cleanup, documentation improvements, etc.

  - type: textarea
    id: description
    attributes:
      label: Task
      description: What needs to be done? Summarize the work and area it affects.
      placeholder: "Update React to v18, Refactor auth module"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Why / Impact
      description: Why is this task valuable? What will improve or be fixed?
      placeholder: "Improve performance, reduce tech debt, enhance security"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type of Chore
      description: What kind of maintenance task is this?
      options:
        - Code change/refactoring
        - UI enhancement
        - Dependency update
        - Configuration change
        - Build/tooling improvement
        - Documentation update
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent or important is this task?
      options:
        - 🔥 High — blocking or urgent
        - ⚙️ Medium — worthwhile soon
        - 💤 Low — nice-to-have or backlog
        - 🧊 Icebox — low priority / future consideration
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Dependencies / Context
      description: Optional — related issues, PRs, or people to notify.
      placeholder: "#1234 (depends on CI change)"
