name: New Issue
description: General issue
title: "[Issue]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide a description of your issue or request.
        If applicable, consider selecting one of the specialized templates from the template picker.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the problem or suggestion?
      placeholder: Describe the issue here
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce / Context
      description: "Optional: how to reproduce, screenshots, or context"
      placeholder: Provide steps, screenshots, or any context
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior / Desired Outcome
      description: "Optional: what you expected to happen"
      placeholder: Explain the expected outcome
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I can reproduce this issue consistently
